---
# Dynamic mode first checks which version is available in the package manager
# If that version satisfies the required version, it installs it via package
# Otherwise, it installs the required version via source
- name: Install rofi OS-specific dynamically
  block:
    - name: Check rofi pkg mgr version
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_distribution }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_os_family }}.yml"
        - "{{ role_path }}/tasks/noauto_check_pkg_mgr_version_{{ ansible_lsb.id }}.yml"
      loop_control:
        loop_var: task_file

    - name: Install rofi from package manager
      ansible.builtin.include_tasks:
        file: noauto_install_package.yml
      when:
        - rofi_pkg_mgr_version is defined
        - rofi_pkg_mgr_version == rofi_version

    - name: Install rofi from source
      ansible.builtin.include_tasks:
        file: noauto_install_source.yml
      when:
        - rofi_pkg_mgr_version is not defined
          or rofi_pkg_mgr_version != rofi_version
